string=str(input("Enter a string:"))
print(type(list(string)))
#l=list(string) #list of characters
l=string.split() 
print("string converted to list",l)
print(type(str(l)))
text=" ".join(l)
print("list converted to string again:",text)
t=tuple(input("enter tuple values seperated by spaces:").split())
print(type(str(t)))
s=" ".join(t)
print("tuple converted to string:",s)
print(type(tuple(s)))
t1=tuple(s.split())
print("string converted to tuple again:",t1)
set=set(input("enter set values seperated by spaces:").split())
print(set)
print(type(list(set)))
lst=list(set)
print("set converted to list:",lst)
t=tuple(lst)
print("list converted to tuple:",t)
s={*t}
print("tuple converted to set again:",s)